# Jobsheet 8 Data Pre-processing

# **Latihan**

# 1. Data Prepration dengan One Hot Encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# membuat data array gender
gender = ['perempuan', 'laki-laki', 'laki-laki', 'perempuan', 'perempuan']

# membuat data frame dari data gender
df = pd.DataFrame({'gender': gender})

# membuat instance dari OneHotEncoder
encoder = OneHotEncoder()

# melakukan encoding pada data frame
encoded_df = pd.DataFrame(encoder.fit_transform(df[['gender']]).toarray(), columns=encoder.get_feature_names_out(['gender']))

# menggabungkan data frame yang sudah di-encode dengan data frame awal
df_encoded = pd.concat([df, encoded_df], axis=1)

# menampilkan hasil
df_encoded

      gender  gender_laki-laki  gender_perempuan
0  perempuan               0.0               1.0
1  laki-laki               1.0               0.0
2  laki-laki               1.0               0.0
3  perempuan               0.0               1.0
4  perempuan               0.0               1.0

# 2. Data Preparation dengan Outlier Removal

In [2]:
import pandas as pd
import numpy as np

# membuat data frame contoh
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': [15, 20, 25, 30, 35, 40, 45, 50, 55, 500]
})

# mencari nilai z-score untuk setiap data point pada kolom B
z_scores = np.abs((df['B'] - df['B'].mean()) / df['B'].std())

# menghilangkan data point yang memiliki z-score lebih besar dari 3
df_clean = df.loc[round(z_scores) < 3]

# menampilkan data frame yang telah di-clean
print(df_clean)

   A   B
0  1  15
1  2  20
2  3  25
3  4  30
4  5  35
5  6  40
6  7  45
7  8  50
8  9  55

# 3.	Data Preparation dengan Normalization

In [3]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
df

    Nama  Gaji  Umur
0   Andi  0.00  0.00
1   Budi  0.25  0.25
2  Cindy  0.50  0.50
3  Diana  0.75  0.75
4    Eka  1.00  1.00
5   lala  0.75  0.25

# 4.	Data Preparation dengan Standarization

In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
print(df)

    Nama  Gaji  Umur
0   Andi  0.00  0.00
1   Budi  0.25  0.25
2  Cindy  0.50  0.50
3  Diana  0.75  0.75
4    Eka  1.00  1.00
5   lala  0.75  0.25

# 5.	Pembuatan DataSet

In [5]:
from sklearn.model_selection import train_test_split
import pandas as pd

# membuat data frame contoh
df = pd.DataFrame({
    'X': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Y': [15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
})

# membagi data menjadi data latih dan data uji dengan rasio 80:20
X_train, X_test, y_train, y_test = train_test_split(df[['X']], df[['Y']], test_size=0.2, random_state=42)

# menampilkan data latih
print('Data Latih')
print('X_train:', X_train)
print('y_train:', y_train)

# menampilkan data uji
print('\nData Uji')
print('X_test:', X_test)
print('y_test:', y_test)

Data Latih
X_train:     X
5   6
0   1
7   8
2   3
9  10
4   5
3   4
6   7
y_train:     Y
5  40
0  15
7  50
2  25
9  60
4  35
3  30
6  45

Data Uji
X_test:    X
8  9
1  2
y_test:     Y
8  55
1  20

# **TUGAS PRAKTIKUM**

Download Dataset

In [6]:
# Import Library yang diperlukan
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

In [7]:
# Load Dataset
df = pd.read_csv('iklan_sosmed.csv', delimiter=';')

In [8]:
# Tampilkan 5 Data Pertama
df.head()

         ID Jenis_Kelamin  Umur        Gaji  Transaksi
0  15624510          Pria    19   285000000          0
1  15810944          Pria    35   300000000          0
2  15668575        Wanita    26   645000000          0
3  15603246        Wanita    27   855000000          0
4  15804002          Pria    19  1140000000          0

In [9]:
# Cek apakah ada data yang kosong (NaN)
df.isnull().sum()

ID               0
Jenis_Kelamin    0
Umur             0
Gaji             0
Transaksi        0
dtype: int64

## Data Preparation - One Hot Encoding

In [10]:
# Cek ada berapa data di kolom Jenis_Kelamin
df.Jenis_Kelamin.unique()

<ArrowStringArray>
['Pria', 'Wanita']
Length: 2, dtype: str

In [11]:
# Lakukan mapping untuk mengubah Pria : 0 dan Wanita : 1
df.Jenis_Kelamin = df.Jenis_Kelamin.map({'Pria':0, 'Wanita':1})

In [12]:
df

           ID  Jenis_Kelamin  Umur        Gaji  Transaksi
0    15624510              0    19   285000000          0
1    15810944              0    35   300000000          0
2    15668575              1    26   645000000          0
3    15603246              1    27   855000000          0
4    15804002              0    19  1140000000          0
..        ...            ...   ...         ...        ...
395  15691863              1    46   615000000          1
396  15706071              0    51   345000000          1
397  15654296              1    50   300000000          1
398  15755018              0    36   495000000          0
399  15594041              1    49   540000000          1

[400 rows x 5 columns]

## Data Preparation - Outlier Removal

In [13]:
# Mencari nilai z-score untuk setiap data point pada kolom Gaji
z_gaji = (df.Gaji - df.Gaji.mean()) / df.Gaji.std()
print('Z-score Gaji:')
print(z_gaji)

# Mencari nilai z-score untuk setiap data point pada kolom Umur
z_umur = (df.Umur - df.Umur.mean()) / df.Umur.std()
print('Z-score Umur:')
print(z_umur)

Z-score Gaji:
0     -1.488183
1     -1.458854
2     -0.784307
3     -0.373714
4      0.183521
         ...
395   -0.842964
396   -1.370870
397   -1.458854
398   -1.077589
399   -0.989604
Name: Gaji, Length: 400, dtype: float64
Z-score Umur:
0     -1.779569
1     -0.253270
2     -1.111813
3     -1.016419
4     -1.779569
         ...
395    0.796060
396    1.273028
397    1.177635
398   -0.157877
399    1.082241
Name: Umur, Length: 400, dtype: float64

In [14]:
# menghilangkan data point yang memiliki z-score lebih besar dari 3 dan menampilkannya
df_clean = df[(z_gaji.abs() <= 3) & (z_umur.abs() <= 3)]
df_clean

           ID  Jenis_Kelamin  Umur        Gaji  Transaksi
0    15624510              0    19   285000000          0
1    15810944              0    35   300000000          0
2    15668575              1    26   645000000          0
3    15603246              1    27   855000000          0
4    15804002              0    19  1140000000          0
..        ...            ...   ...         ...        ...
395  15691863              1    46   615000000          1
396  15706071              0    51   345000000          1
397  15654296              1    50   300000000          1
398  15755018              0    36   495000000          0
399  15594041              1    49   540000000          1

[400 rows x 5 columns]

## Data Preparation - Mengambil Dataset

In [15]:
# Melihat korelasi antar kolom
df_clean.corr()

                     ID  Jenis_Kelamin      Umur      Gaji  Transaksi
ID             1.000000       0.025249 -0.000721  0.071097   0.007120
Jenis_Kelamin  0.025249       1.000000  0.073741  0.060435   0.042469
Umur          -0.000721       0.073741  1.000000  0.155238   0.622454
Gaji           0.071097       0.060435  0.155238  1.000000   0.362083
Transaksi      0.007120       0.042469  0.622454  0.362083   1.000000

In [16]:
# Mengambil Umur dan Gaji sebagai Variabel Data dan Transaksi sebagai Variabel Label
X = df.iloc[:,2:-1]
y = df.iloc[:, -1]

In [17]:
# Bagi data menjadi 80% data latih dan 20% data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('Jumlah data latih:', X_train.shape[0])
print('Jumlah data uji:', X_test.shape[0])

Jumlah data latih: 320
Jumlah data uji: 80

## Data Preparation - Normalization

In [18]:
# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.02380952, 0.02962963],
       [0.4047619 , 0.03703704],
       [0.19047619, 0.20740741],
       [0.21428571, 0.31111111],
       [0.02380952, 0.45185185],
       [0.21428571, 0.31851852],
       [0.21428571, 0.51111111],
       [0.33333333, 1.        ],
       [0.16666667, 0.13333333],
       [0.4047619 , 0.37037037],
       [0.19047619, 0.48148148],
       [0.19047619, 0.27407407],
       [0.04761905, 0.52592593],
       [0.33333333, 0.02222222],
       [0.        , 0.4962963 ],
       [0.26190476, 0.48148148],
       [0.69047619, 0.07407407],
       [0.64285714, 0.08148148],
       [0.66666667, 0.0962963 ],
       [0.71428571, 0.1037037 ],
       [0.64285714, 0.05185185],
       [0.69047619, 0.25185185],
       [0.71428571, 0.19259259],
       [0.64285714, 0.05185185],
       [0.66666667, 0.05925926],
       [0.69047619, 0.03703704],
       [0.73809524, 0.0962963 ],
       [0.69047619, 0.11111111],
       [0.26190476, 0.20740741],
       [0.30952381, 0.02222222],
       [0.30952381, 0.43703704],
       [0.21428571, 0.9037037 ],
       [0.07142857, 0.00740741],
       [0.23809524, 0.21481481],
       [0.21428571, 0.55555556],
       [0.4047619 , 0.08888889],
       [0.35714286, 0.0962963 ],
       [0.28571429, 0.25185185],
       [0.19047619, 0.42222222],
       [0.21428571, 0.11851852],
       [0.21428571, 0.01481481],
       [0.35714286, 0.26666667],
       [0.4047619 , 0.68888889],
       [0.28571429, 0.        ],
       [0.23809524, 0.51111111],
       [0.11904762, 0.03703704],
       [0.16666667, 0.47407407],
       [0.21428571, 0.28888889],
       [0.28571429, 0.88888889],
       [0.30952381, 0.54814815],
       [0.14285714, 0.12592593],
       [0.        , 0.21481481],
       [0.26190476, 0.5037037 ],
       [0.4047619 , 0.05925926],
       [0.21428571, 0.31851852],
       [0.14285714, 0.2962963 ],
       [0.11904762, 0.24444444],
       [0.23809524, 0.47407407],
       [0.0952381 , 0.02222222],
       [0.33333333, 0.75555556],
       [0.21428571, 0.03703704],
       [0.16666667, 0.53333333],
       [0.11904762, 0.37777778],
       [0.33333333, 0.77777778],
       [0.97619048, 0.5037037 ],
       [0.14285714, 0.31851852],
       [0.14285714, 0.02962963],
       [0.11904762, 0.4962963 ],
       [0.0952381 , 0.35555556],
       [0.30952381, 0.39259259],
       [0.16666667, 0.48148148],
       [0.14285714, 0.08888889],
       [0.04761905, 0.05925926],
       [0.35714286, 0.72592593],
       [0.33333333, 0.02222222],
       [0.38095238, 0.71851852],
       [0.        , 0.27407407],
       [0.0952381 , 0.08888889],
       [0.23809524, 0.53333333],
       [0.19047619, 0.01481481],
       [0.28571429, 0.48148148],
       [0.5       , 0.2       ],
       [0.04761905, 0.25185185],
       [0.4047619 , 0.54074074],
       [0.28571429, 0.34814815],
       [0.30952381, 0.76296296],
       [0.14285714, 0.2962963 ],
       [0.23809524, 0.51851852],
       [0.19047619, 0.48888889],
       [0.4047619 , 0.25925926],
       [0.0952381 , 0.48888889],
       [0.28571429, 0.74814815],
       [0.19047619, 0.        ],
       [0.26190476, 0.0962963 ],
       [0.26190476, 0.5037037 ],
       [0.4047619 , 0.21481481],
       [0.4047619 , 0.07407407],
       [0.23809524, 0.8       ],
       [0.4047619 , 0.42962963],
       [0.23809524, 0.16296296],
       [0.21428571, 0.54074074],
       [0.23809524, 0.32592593],
       [0.33333333, 0.52592593],
       [0.35714286, 0.99259259],
       [0.02380952, 0.04444444],
       [0.07142857, 0.42222222],
       [0.19047619, 0.14814815],
       [0.21428571, 0.54814815],
       [0.19047619, 0.52592593],
       [0.47619048, 0.48148148],
       [0.5       , 0.41481481],
       [0.45238095, 0.41481481],
       [0.47619048, 0.34074074],
       [0.45238095, 0.2962963 ],
       [0.57142857, 0.48148148],
       [0.52380952, 0.31111111],
       [0.4047619 , 0.44444444],
       [0.42857143, 0.27407407],
       [0.52380952, 0.32592593],
       [0.54761905, 0.32592593],
       [0.42857143, 0.44444444],
       [0.45238095, 0.42222222],
       [0.52380952, 0.44444444],
       [0.4047619 , 0.28148148],
       [0.54761905, 0.26666667],
       [0.5       , 0.34074074],
       [0.57142857, 0.37037037],
       [0.19047619, 0.12592593],
       [0.28571429, 0.01481481],
       [0.19047619, 0.51111111],
       [0.30952381, 0.31851852],
       [0.35714286, 0.11851852],
       [0.28571429, 0.53333333],
       [0.07142857, 0.39259259],
       [0.23809524, 0.2962963 ],
       [0.11904762, 0.35555556],
       [0.04761905, 0.4962963 ],
       [0.28571429, 0.68148148],
       [0.23809524, 0.32592593],
       [0.02380952, 0.07407407],
       [0.02380952, 0.51851852],
       [0.        , 0.39259259],
       [0.4047619 , 0.32592593],
       [0.28571429, 0.54814815],
       [0.38095238, 0.07407407],
       [0.14285714, 0.54814815],
       [0.21428571, 0.6       ],
       [0.54761905, 0.11111111],
       [0.26190476, 0.34074074],
       [0.04761905, 0.43703704],
       [0.19047619, 0.        ],
       [0.54761905, 0.22222222],
       [0.30952381, 0.45185185],
       [0.42857143, 0.25925926],
       [0.52380952, 0.23703704],
       [0.30952381, 0.        ],
       [0.66666667, 0.32592593],
       [0.26190476, 0.44444444],
       [0.19047619, 0.11111111],
       [0.33333333, 0.88888889],
       [0.33333333, 0.62962963],
       [0.16666667, 0.55555556],
       [0.45238095, 0.13333333],
       [0.4047619 , 0.17037037],
       [0.35714286, 0.4       ],
       [0.        , 0.52592593],
       [0.0952381 , 0.2962963 ],
       [0.4047619 , 0.41481481],
       [0.26190476, 0.98518519],
       [0.26190476, 0.23703704],
       [0.07142857, 0.54074074],
       [0.38095238, 0.74074074],
       [0.19047619, 0.76296296],
       [0.38095238, 0.20740741],
       [0.38095238, 0.42222222],
       [0.11904762, 0.0962963 ],
       [0.4047619 , 0.23703704],
       [0.16666667, 0.05185185],
       [0.14285714, 0.05925926],
       [0.30952381, 0.14074074],
       [0.19047619, 0.00740741],
       [0.30952381, 0.41481481],
       [0.33333333, 0.75555556],
       [0.35714286, 0.20740741],
       [0.35714286, 0.33333333],
       [0.30952381, 0.37777778],
       [0.04761905, 0.4962963 ],
       [0.35714286, 0.19259259],
       [0.4047619 , 0.42222222],
       [0.23809524, 0.12592593],
       [0.14285714, 0.51111111],
       [0.02380952, 0.08148148],
       [0.26190476, 0.20740741],
       [0.02380952, 0.40740741],
       [0.23809524, 0.54814815],
       [0.38095238, 0.20740741],
       [0.28571429, 0.47407407],
       [0.04761905, 0.15555556],
       [0.19047619, 0.48148148],
       [0.4047619 , 0.05185185],
       [0.4047619 , 0.17777778],
       [0.73809524, 0.43703704],
       [0.5       , 0.88148148],
       [0.54761905, 0.41481481],
       [0.95238095, 0.63703704],
       [0.69047619, 0.23703704],
       [0.88095238, 0.85185185],
       [0.80952381, 0.73333333],
       [0.52380952, 0.94074074],
       [0.66666667, 0.05185185],
       [0.71428571, 0.6       ],
       [0.80952381, 1.        ],
       [0.97619048, 0.2       ],
       [0.4047619 , 0.31851852],
       [0.69047619, 0.20740741],
       [1.        , 0.68888889],
       [0.73809524, 0.37037037],
       [0.52380952, 0.46666667],
       [0.66666667, 0.6       ],
       [0.97619048, 0.94814815],
       [0.54761905, 0.48148148],
       [0.4047619 , 0.56296296],
       [0.45238095, 0.95555556],
       [1.        , 0.64444444],
       [0.4047619 , 0.33333333],
       [0.45238095, 0.28148148],
       [0.42857143, 0.82222222],
       [0.9047619 , 0.87407407],
       [0.52380952, 0.42222222],
       [0.57142857, 0.48148148],
       [0.4047619 , 0.97777778],
       [0.5       , 0.2       ],
       [0.52380952, 0.68148148],
       [0.73809524, 0.52592593],
       [0.47619048, 0.71851852],
       [0.66666667, 0.47407407],
       [0.52380952, 0.31111111],
       [0.45238095, 0.48148148],
       [0.66666667, 0.4962963 ],
       [0.83333333, 0.94814815],
       [0.57142857, 0.99259259],
       [0.47619048, 0.32592593],
       [0.76190476, 0.54074074],
       [0.9047619 , 0.65925926],
       [0.54761905, 0.42222222],
       [0.78571429, 0.97037037],
       [0.4047619 , 0.25925926],
       [0.92857143, 0.79259259],
       [0.54761905, 0.27407407],
       [0.4047619 , 0.60740741],
       [0.61904762, 0.17777778],
       [0.45238095, 0.27407407],
       [0.71428571, 0.88148148],
       [0.45238095, 0.97037037],
       [0.76190476, 0.21481481],
       [0.80952381, 0.55555556],
       [0.54761905, 0.42222222],
       [0.52380952, 0.31111111],
       [0.95238095, 0.59259259],
       [0.64285714, 0.85925926],
       [0.4047619 , 0.45925926],
       [0.42857143, 0.95555556],
       [0.88095238, 0.81481481],
       [0.4047619 , 0.42222222],
       [0.71428571, 0.55555556],
       [0.57142857, 0.68888889],
       [0.52380952, 0.44444444],
       [0.45238095, 0.43703704],
       [0.69047619, 0.95555556],
       [0.52380952, 0.34074074],
       [0.5952381 , 0.87407407],
       [0.97619048, 0.45185185],
       [1.        , 0.2       ],
       [0.5       , 0.67407407],
       [0.92857143, 0.08148148],
       [0.92857143, 0.43703704],
       [0.47619048, 0.41481481],
       [0.73809524, 0.54074074],
       [0.80952381, 0.17037037],
       [0.76190476, 0.15555556],
       [0.97619048, 0.54074074],
       [0.4047619 , 0.34074074],
       [0.45238095, 0.40740741],
       [0.80952381, 0.04444444],
       [0.71428571, 0.93333333],
       [0.45238095, 0.57777778],
       [0.45238095, 0.34814815],
       [0.71428571, 0.91111111],
       [0.54761905, 0.47407407],
       [0.45238095, 0.46666667],
       [0.5       , 0.88148148],
       [0.73809524, 0.54814815],
       [0.88095238, 0.17777778],
       [0.45238095, 0.45925926],
       [0.4047619 , 0.31111111],
       [0.42857143, 0.35555556],
       [0.57142857, 0.42962963],
       [0.5952381 , 0.71851852],
       [0.64285714, 0.47407407],
       [0.66666667, 0.75555556],
       [0.95238095, 0.17037037],
       [0.71428571, 0.43703704],
       [0.45238095, 0.9037037 ],
       [0.45238095, 0.47407407],
       [0.52380952, 0.33333333],
       [0.57142857, 0.28888889],
       [0.78571429, 0.88148148],
       [0.69047619, 0.72592593],
       [0.42857143, 0.81481481],
       [0.47619048, 0.25925926],
       [0.57142857, 0.40740741],
       [0.5       , 0.6       ],
       [0.47619048, 0.25925926],
       [0.73809524, 0.93333333],
       [0.5       , 0.47407407],
       [0.5       , 0.44444444],
       [0.85714286, 0.65925926],
       [0.4047619 , 0.2962963 ],
       [0.64285714, 0.12592593],
       [0.42857143, 0.33333333],
       [0.80952381, 0.91111111],
       [0.83333333, 0.4962963 ],
       [0.54761905, 0.27407407],
       [0.71428571, 0.11111111],
       [0.71428571, 0.85925926],
       [0.54761905, 0.33333333],
       [0.54761905, 0.42222222],
       [0.57142857, 0.44444444],
       [0.42857143, 0.76296296],
       [0.69047619, 0.68148148],
       [0.47619048, 0.26666667],
       [0.71428571, 0.77037037],
       [0.57142857, 0.37037037],
       [0.52380952, 0.37037037],
       [0.92857143, 0.33333333],
       [0.42857143, 0.28888889],
       [0.95238095, 0.95555556],
       [0.4047619 , 0.47407407],
       [0.47619048, 0.2962963 ],
       [0.5       , 0.79259259],
       [0.83333333, 0.65925926],
       [0.4047619 , 0.44444444],
       [0.47619048, 0.37037037],
       [0.69047619, 0.26666667],
       [0.69047619, 0.66666667],
       [0.54761905, 0.35555556],
       [0.83333333, 0.42222222],
       [0.85714286, 0.68888889],
       [0.5       , 0.45925926],
       [0.47619048, 0.34074074],
       [0.47619048, 0.72592593],
       [0.45238095, 0.44444444],
       [0.57142857, 0.55555556],
       [0.45238095, 0.31111111],
       [0.42857143, 0.62222222],
       [1.        , 0.14074074],
       [0.85714286, 0.40740741],
       [0.54761905, 0.42222222],
       [0.52380952, 0.41481481],
       [0.57142857, 0.28888889],
       [0.5952381 , 0.84444444],
       [0.83333333, 0.14074074],
       [0.69047619, 0.25925926],
       [0.57142857, 0.47407407],
       [0.57142857, 0.65925926],
       [0.97619048, 0.1037037 ],
       [0.95238095, 0.23703704],
       [0.66666667, 0.54074074],
       [0.47619048, 0.41481481],
       [0.85714286, 0.08148148],
       [1.        , 0.22962963],
       [1.        , 0.5037037 ],
       [0.5       , 0.42962963],
       [0.97619048, 0.85185185],
       [0.45238095, 0.48148148],
       [0.66666667, 0.12592593],
       [0.66666667, 0.43703704],
       [0.57142857, 0.28148148],
       [0.54761905, 0.53333333],
       [0.95238095, 0.05925926],
       [0.57142857, 0.36296296],
       [0.71428571, 0.13333333],
       [0.61904762, 0.91851852],
       [0.73809524, 0.0962963 ],
       [0.92857143, 0.13333333],
       [0.9047619 , 0.33333333],
       [0.73809524, 0.17777778],
       [0.5       , 0.41481481],
       [0.69047619, 0.14074074],
       [0.71428571, 0.14814815],
       [0.71428571, 0.13333333],
       [0.69047619, 0.05925926],
       [0.64285714, 0.22222222],
       [1.        , 0.2       ],
       [0.5       , 0.32592593],
       [0.66666667, 0.19259259],
       [0.78571429, 0.05925926],
       [0.76190476, 0.03703704],
       [0.42857143, 0.13333333],
       [0.73809524, 0.15555556]])

## Data Preparation - Normalization

In [19]:
# membuat model Decision Tree
model = DecisionTreeClassifier()

# melakukan 5-fold cross validation
scores = cross_val_score(model, X, y, cv=5)

# menampilkan hasil cross validation
print('Hasil Cross Validation tiap fold:', scores)
print('Rata-rata Akurasi:', scores.mean())

Hasil Cross Validation tiap fold: [0.75   0.9    0.8125 0.75   0.775 ]
Rata-rata Akurasi: 0.7975